from typing import Protocol, ClassVar, TypeVar, Optional

from PySide6.QtCore import QObject

from flow3r.core.streaming.abc.stream import IStream


class IConnectableSignal(Protocol):
    def connect(self, slot): ...
    def disconnect(self, slot): ...


TDesc = TypeVar("TDesc")
TData = TypeVar("TData")

class IVisualizerHandle(Protocol[TDesc, TData]):
    @property
    def format(self) -> Optional[TDesc]: ...
    @property
    def item(self) -> Optional[TData]: ...
    @property
    def error(self) -> Optional[Exception]: ...
    @property
    def completed(self) -> bool: ...
    @property
    def format_changed(self) -> IConnectableSignal: ...
    @property
    def item_changed(self) -> IConnectableSignal: ...
    @property
    def error_changed(self) -> IConnectableSignal: ...
    @property
    def completed_changed(self) -> IConnectableSignal: ...

    def set_format(self, fmt: TDesc) -> None: ...
    def set_item(self, item: TData) -> None: ...
    def set_error(self, error: Optional[Exception]) -> None: ...
    def set_completed(self, completed: bool) -> None: ...

    def dispose(self): ...


class QVisualizerMeta(type(QObject), type(IVisualizerHandle)):
    pass
