from typing import Protocol, Any


class IVisualizer(Protocol):
    def visualize(self, data: dict): ...


class IVisualizerType(Protocol):
    @property
    def name(self) -> str: ...
    @property
    def widget_factory(self): ...
    def accepts(self, desc: Any) -> bool: ...
