from aaaflow3r.core.pipeline.abc.pipeline_type import IPipelineType
from aaaflow3r.plugins.test.pipeline.test.pipeline import TestPipeline


class TestPipelineType(IPipelineType[TConfig, TestPipeline]):
    @property
    def name(self) -> str: ...
    @property
    def category(self) -> str: ...
    def get_config_factory(self) -> Callable[[], TConfig]: ...
    def get_config_widget_factory(self) -> Callable[[TConfig, QWidget], QWidget]: ...
    def get_pipeline_factory(self) -> Callable[[TConfig], TestPipeline]: ...